// ========================
// HitFlick Låtbank
// ========================

export const songCategories = {

  // =======================
  // 50-TAL (40 låtar)
  // =======================
  "50s": [
    { id: "50s-001", title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
    { id: "50s-002", title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1954 },
    { id: "50s-003", title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958 },
    { id: "50s-004", title: "Great Balls of Fire", artist: "Jerry Lee Lewis", year: 1957 },
    { id: "50s-005", title: "Blue Suede Shoes", artist: "Carl Perkins", year: 1956 },
    { id: "50s-006", title: "Tutti Frutti", artist: "Little Richard", year: 1955 },
    { id: "50s-007", title: "La Bamba", artist: "Ritchie Valens", year: 1958 },
    { id: "50s-008", title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
    { id: "50s-009", title: "That'll Be the Day", artist: "Buddy Holly", year: 1957 },
    { id: "50s-010", title: "Peggy Sue", artist: "Buddy Holly", year: 1957 },
    { id: "50s-011", title: "All Shook Up", artist: "Elvis Presley", year: 1957 },
    { id: "50s-012", title: "Heartbreak Hotel", artist: "Elvis Presley", year: 1956 },
    { id: "50s-013", title: "Why Do Fools Fall in Love", artist: "Frankie Lymon & The Teenagers", year: 1956 },
    { id: "50s-014", title: "Summertime Blues", artist: "Eddie Cochran", year: 1958 },
    { id: "50s-015", title: "Chances Are", artist: "Johnny Mathis", year: 1957 },
    { id: "50s-016", title: "Diana", artist: "Paul Anka", year: 1957 },
    { id: "50s-017", title: "Love Me Tender", artist: "Elvis Presley", year: 1956 },
    { id: "50s-018", title: "Sh-Boom", artist: "The Chords", year: 1954 },
    { id: "50s-019", title: "Lonely Teardrops", artist: "Jackie Wilson", year: 1958 },
    { id: "50s-020", title: "The Great Pretender", artist: "The Platters", year: 1955 },
    { id: "50s-021", title: "Only You", artist: "The Platters", year: 1955 },
    { id: "50s-022", title: "Tequila", artist: "The Champs", year: 1958 },
    { id: "50s-023", title: "At the Hop", artist: "Danny & The Juniors", year: 1957 },
    { id: "50s-024", title: "Wake Up Little Susie", artist: "The Everly Brothers", year: 1957 },
    { id: "50s-025", title: "Bye Bye Love", artist: "The Everly Brothers", year: 1957 },
    { id: "50s-026", title: "Yakety Yak", artist: "The Coasters", year: 1958 },
    { id: "50s-027", title: "Rave On", artist: "Buddy Holly", year: 1958 },
    { id: "50s-028", title: "Rebel Rouser", artist: "Duane Eddy", year: 1958 },
    { id: "50s-029", title: "Mack the Knife", artist: "Bobby Darin", year: 1959 },
    { id: "50s-030", title: "Dream Lover", artist: "Bobby Darin", year: 1959 },
    { id: "50s-031", title: "Stupid Cupid", artist: "Connie Francis", year: 1958 },
    { id: "50s-032", title: "Volare", artist: "Domenico Modugno", year: 1958 },
    { id: "50s-033", title: "Mr. Sandman", artist: "The Chordettes", year: 1954 },
    { id: "50s-034", title: "Earth Angel", artist: "The Penguins", year: 1954 },
    { id: "50s-035", title: "Sixteen Tons", artist: "Tennessee Ernie Ford", year: 1955 },
    { id: "50s-036", title: "Come Go With Me", artist: "The Del-Vikings", year: 1957 },
    { id: "50s-037", title: "A Teenager in Love", artist: "Dion & The Belmonts", year: 1959 },
    { id: "50s-038", title: "Chantilly Lace", artist: "The Big Bopper", year: 1958 },
    { id: "50s-039", title: "Smoke Gets in Your Eyes", artist: "The Platters", year: 1958 },
    { id: "50s-040", title: "Whole Lotta Shakin' Goin' On", artist: "Jerry Lee Lewis", year: 1957 }
  ],

  // =======================
  // 60-TAL (50 låtar)
  // =======================
  "60s": [
    { id: "60s-001", title: "Hey Jude", artist: "The Beatles", year: 1968 },
    { id: "60s-002", title: "I Want to Hold Your Hand", artist: "The Beatles", year: 1963 },
    { id: "60s-003", title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
    { id: "60s-004", title: "Like a Rolling Stone", artist: "Bob Dylan", year: 1965 },
    { id: "60s-005", title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
    { id: "60s-006", title: "Respect", artist: "Aretha Franklin", year: 1967 },
    { id: "60s-007", title: "My Girl", artist: "The Temptations", year: 1964 },
    { id: "60s-008", title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
    { id: "60s-009", title: "Light My Fire", artist: "The Doors", year: 1967 },
    { id: "60s-010", title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", year: 1968 },
    { id: "60s-011", title: "Sittin' On The Dock of the Bay", artist: "Otis Redding", year: 1968 },
    { id: "60s-012", title: "Stand By Me", artist: "Ben E. King", year: 1961 },
    { id: "60s-013", title: "What a Wonderful World", artist: "Louis Armstrong", year: 1967 },
    { id: "60s-014", title: "The Sound of Silence", artist: "Simon & Garfunkel", year: 1964 },
    { id: "60s-015", title: "California Dreamin'", artist: "The Mamas & The Papas", year: 1965 },
    { id: "60s-016", title: "A Day in the Life", artist: "The Beatles", year: 1967 },
    { id: "60s-017", title: "Help!", artist: "The Beatles", year: 1965 },
    { id: "60s-018", title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
    { id: "60s-019", title: "Twist and Shout", artist: "The Beatles", year: 1963 },
    { id: "60s-020", title: "You Really Got Me", artist: "The Kinks", year: 1964 },
    { id: "60s-021", title: "Sunshine of Your Love", artist: "Cream", year: 1967 },
    { id: "60s-022", title: "Runaway", artist: "Del Shannon", year: 1961 },
    { id: "60s-023", title: "Be My Baby", artist: "The Ronettes", year: 1963 },
    { id: "60s-024", title: "Unchained Melody", artist: "The Righteous Brothers", year: 1965 },
    { id: "60s-025", title: "The House of the Rising Sun", artist: "The Animals", year: 1964 },
    { id: "60s-026", title: "Oh, Pretty Woman", artist: "Roy Orbison", year: 1964 },
    { id: "60s-027", title: "A Whiter Shade of Pale", artist: "Procol Harum", year: 1967 },
    { id: "60s-028", title: "Mrs. Robinson", artist: "Simon & Garfunkel", year: 1968 },
    { id: "60s-029", title: "I Got You (I Feel Good)", artist: "James Brown", year: 1965 },
    { id: "60s-030", title: "Sugar, Sugar", artist: "The Archies", year: 1969 },
    { id: "60s-031", title: "It's Now or Never", artist: "Elvis Presley", year: 1960 },
    { id: "60s-032", title: "I Saw Her Standing There", artist: "The Beatles", year: 1963 },
    { id: "60s-033", title: "In My Life", artist: "The Beatles", year: 1965 },
    { id: "60s-034", title: "Wouldn't It Be Nice", artist: "The Beach Boys", year: 1966 },
    { id: "60s-035", title: "White Rabbit", artist: "Jefferson Airplane", year: 1967 },
    { id: "60s-036", title: "Penny Lane", artist: "The Beatles", year: 1967 },
    { id: "60s-037", title: "Georgia on My Mind", artist: "Ray Charles", year: 1960 },
    { id: "60s-038", title: "Baby Love", artist: "The Supremes", year: 1964 },
    { id: "60s-039", title: "Reach Out I'll Be There", artist: "The Four Tops", year: 1966 },
    { id: "60s-040", title: "She Loves You", artist: "The Beatles", year: 1963 },
    { id: "60s-041", title: "Turn! Turn! Turn!", artist: "The Byrds", year: 1965 },
    { id: "60s-042", title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
    { id: "60s-043", title: "Born to Be Wild", artist: "Steppenwolf", year: 1968 },
    { id: "60s-044", title: "Hey Joe", artist: "Jimi Hendrix", year: 1966 },
    { id: "60s-045", title: "Brown Eyed Girl", artist: "Van Morrison", year: 1967 },
    { id: "60s-046", title: "These Boots Are Made for Walkin'", artist: "Nancy Sinatra", year: 1966 },
    { id: "60s-047", title: "The Twist", artist: "Chubby Checker", year: 1960 },
    { id: "60s-048", title: "Dancing in the Street", artist: "Martha & The Vandellas", year: 1964 },
    { id: "60s-049", title: "It's the Same Old Song", artist: "The Four Tops", year: 1965 },
    { id: "60s-050", title: "Eleanor Rigby", artist: "The Beatles", year: 1966 }
  ],
    // =======================
  // 70-TAL (50 låtar)
  // =======================
  "70s": [
    { id: "70s-001", title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
    { id: "70s-002", title: "Dancing Queen", artist: "ABBA", year: 1976 },
    { id: "70s-003", title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
    { id: "70s-004", title: "Hotel California", artist: "Eagles", year: 1976 },
    { id: "70s-005", title: "Imagine", artist: "John Lennon", year: 1971 },
    { id: "70s-006", title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
    { id: "70s-007", title: "Superstition", artist: "Stevie Wonder", year: 1972 },
    { id: "70s-008", title: "Let It Be", artist: "The Beatles", year: 1970 },
    { id: "70s-009", title: "Dream On", artist: "Aerosmith", year: 1973 },
    { id: "70s-010", title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
    { id: "70s-011", title: "Le Freak", artist: "Chic", year: 1978 },
    { id: "70s-012", title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
    { id: "70s-013", title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
    { id: "70s-014", title: "American Pie", artist: "Don McLean", year: 1971 },
    { id: "70s-015", title: "Roxanne", artist: "The Police", year: 1978 },
    { id: "70s-016", title: "Smoke on the Water", artist: "Deep Purple", year: 1972 },
    { id: "70s-017", title: "Tiny Dancer", artist: "Elton John", year: 1971 },
    { id: "70s-018", title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
    { id: "70s-019", title: "London Calling", artist: "The Clash", year: 1979 },
    { id: "70s-020", title: "The Joker", artist: "Steve Miller Band", year: 1973 },
    { id: "70s-021", title: "Heart of Glass", artist: "Blondie", year: 1978 },
    { id: "70s-022", title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
    { id: "70s-023", title: "Shining Star", artist: "Earth, Wind & Fire", year: 1975 },
    { id: "70s-024", title: "September", artist: "Earth, Wind & Fire", year: 1978 },
    { id: "70s-025", title: "We Are the Champions", artist: "Queen", year: 1977 },
    { id: "70s-026", title: "We Will Rock You", artist: "Queen", year: 1977 },
    { id: "70s-027", title: "More Than a Feeling", artist: "Boston", year: 1976 },
    { id: "70s-028", title: "Barracuda", artist: "Heart", year: 1977 },
    { id: "70s-029", title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", year: 1970 },
    { id: "70s-030", title: "Jolene", artist: "Dolly Parton", year: 1973 },
    { id: "70s-031", title: "Maggie May", artist: "Rod Stewart", year: 1971 },
    { id: "70s-032", title: "Lean on Me", artist: "Bill Withers", year: 1972 },
    { id: "70s-033", title: "Take It Easy", artist: "Eagles", year: 1972 },
    { id: "70s-034", title: "You're the One That I Want", artist: "John Travolta & Olivia Newton-John", year: 1978 },
    { id: "70s-035", title: "YMCA", artist: "Village People", year: 1978 },
    { id: "70s-036", title: "Kung Fu Fighting", artist: "Carl Douglas", year: 1974 },
    { id: "70s-037", title: "Let’s Stay Together", artist: "Al Green", year: 1971 },
    { id: "70s-038", title: "Best of My Love", artist: "The Emotions", year: 1977 },
    { id: "70s-039", title: "Take a Chance on Me", artist: "ABBA", year: 1977 },
    { id: "70s-040", title: "Waterloo", artist: "ABBA", year: 1974 },
    { id: "70s-041", title: "Baker Street", artist: "Gerry Rafferty", year: 1978 },
    { id: "70s-042", title: "Long Train Runnin'", artist: "The Doobie Brothers", year: 1973 },
    { id: "70s-043", title: "Have You Ever Seen the Rain?", artist: "Creedence Clearwater Revival", year: 1970 },
    { id: "70s-044", title: "Paranoid", artist: "Black Sabbath", year: 1970 },
    { id: "70s-045", title: "The Chain", artist: "Fleetwood Mac", year: 1977 },
    { id: "70s-046", title: "Stay With Me", artist: "Faces", year: 1971 },
    { id: "70s-047", title: "Highway to Hell", artist: "AC/DC", year: 1979 },
    { id: "70s-048", title: "Anarchy in the U.K.", artist: "Sex Pistols", year: 1976 },
    { id: "70s-049", title: "Mr. Blue Sky", artist: "ELO", year: 1977 },
    { id: "70s-050", title: "Video Killed the Radio Star", artist: "The Buggles", year: 1979 }
  ],

  // =======================
  // 80-TAL (50 låtar)
  // =======================
  "80s": [
    { id: "80s-001", title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
    { id: "80s-002", title: "Take On Me", artist: "a-ha", year: 1984 },
    { id: "80s-003", title: "The Final Countdown", artist: "Europe", year: 1986 },
    { id: "80s-004", title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
    { id: "80s-005", title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
    { id: "80s-006", title: "Every Breath You Take", artist: "The Police", year: 1983 },
    { id: "80s-007", title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
    { id: "80s-008", title: "Africa", artist: "Toto", year: 1982 },
    { id: "80s-009", title: "With or Without You", artist: "U2", year: 1987 },
    { id: "80s-010", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
    { id: "80s-011", title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
    { id: "80s-012", title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987 },
    { id: "80s-013", title: "Like a Prayer", artist: "Madonna", year: 1989 },
    { id: "80s-014", title: "Careless Whisper", artist: "George Michael", year: 1984 },
    { id: "80s-015", title: "Beat It", artist: "Michael Jackson", year: 1982 },
    { id: "80s-016", title: "When Doves Cry", artist: "Prince", year: 1984 },
    { id: "80s-017", title: "Jump", artist: "Van Halen", year: 1984 },
    { id: "80s-018", title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: 1983 },
    { id: "80s-019", title: "Karma Chameleon", artist: "Culture Club", year: 1983 },
    { id: "80s-020", title: "Wake Me Up Before You Go-Go", artist: "Wham!", year: 1984 },
    { id: "80s-021", title: "Take My Breath Away", artist: "Berlin", year: 1986 },
    { id: "80s-022", title: "Another One Bites the Dust", artist: "Queen", year: 1980 },
    { id: "80s-023", title: "Tainted Love", artist: "Soft Cell", year: 1981 },
    { id: "80s-024", title: "Time After Time", artist: "Cyndi Lauper", year: 1983 },
    { id: "80s-025", title: "Footloose", artist: "Kenny Loggins", year: 1984 },
    { id: "80s-026", title: "The Power of Love", artist: "Huey Lewis & the News", year: 1985 },
    { id: "80s-027", title: "Don't You (Forget About Me)", artist: "Simple Minds", year: 1985 },
    { id: "80s-028", title: "In the Air Tonight", artist: "Phil Collins", year: 1981 },
    { id: "80s-029", title: "Waiting for a Girl Like You", artist: "Foreigner", year: 1981 },
    { id: "80s-030", title: "Broken Wings", artist: "Mr. Mister", year: 1985 },
    { id: "80s-031", title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
    { id: "80s-032", title: "Call Me", artist: "Blondie", year: 1980 },
    { id: "80s-033", title: "Should I Stay or Should I Go", artist: "The Clash", year: 1982 },
    { id: "80s-034", title: "Modern Love", artist: "David Bowie", year: 1983 },
    { id: "80s-035", title: "Man in the Mirror", artist: "Michael Jackson", year: 1988 },
    { id: "80s-036", title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987 },
    { id: "80s-037", title: "Walk Like an Egyptian", artist: "The Bangles", year: 1986 },
    { id: "80s-038", title: "Sweet Love", artist: "Anita Baker", year: 1986 },
    { id: "80s-039", title: "Summer of '69", artist: "Bryan Adams", year: 1984 },
    { id: "80s-040", title: "The Safety Dance", artist: "Men Without Hats", year: 1982 },
    { id: "80s-041", title: "Here I Go Again", artist: "Whitesnake", year: 1987 },
    { id: "80s-042", title: "Take Me Home Tonight", artist: "Eddie Money", year: 1986 },
    { id: "80s-043", title: "Somebody’s Watching Me", artist: "Rockwell", year: 1984 },
    { id: "80s-044", title: "Everybody Wants to Rule the World", artist: "Tears for Fears", year: 1985 },
    { id: "80s-045", title: "Purple Rain", artist: "Prince", year: 1984 },
    { id: "80s-046", title: "Ghostbusters", artist: "Ray Parker Jr.", year: 1984 },
    { id: "80s-047", title: "Pride (In the Name of Love)", artist: "U2", year: 1984 },
    { id: "80s-048", title: "Like a Virgin", artist: "Madonna", year: 1984 },
    { id: "80s-049", title: "Born in the U.S.A.", artist: "Bruce Springsteen", year: 1984 },
    { id: "80s-050", title: "The Way You Make Me Feel", artist: "Michael Jackson", year: 1987 }
  ],

  // =======================
  // 90-TAL (50 låtar)
  // =======================
  "90s": [
    { id: "90s-001", title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
    { id: "90s-002", title: "Wonderwall", artist: "Oasis", year: 1995 },
    { id: "90s-003", title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
    { id: "90s-004", title: "Creep", artist: "Radiohead", year: 1992 },
    { id: "90s-005", title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
    { id: "90s-006", title: "No Scrubs", artist: "TLC", year: 1999 },
    { id: "90s-007", title: "Black Hole Sun", artist: "Soundgarden", year: 1994 },
    { id: "90s-008", title: "Killing Me Softly", artist: "The Fugees", year: 1996 },
    { id: "90s-009", title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
    { id: "90s-010", title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
    { id: "90s-011", title: "Waterfalls", artist: "TLC", year: 1995 },
    { id: "90s-012", title: "No Diggity", artist: "Blackstreet", year: 1996 },
    { id: "90s-013", title: "Enter Sandman", artist: "Metallica", year: 1991 },
    { id: "90s-014", title: "November Rain", artist: "Guns N' Roses", year: 1992 },
    { id: "90s-015", title: "Gangsta’s Paradise", artist: "Coolio", year: 1995 },
    { id: "90s-016", title: "Kiss from a Rose", artist: "Seal", year: 1994 },
    { id: "90s-017", title: "Zombie", artist: "The Cranberries", year: 1994 },
    { id: "90s-018", title: "Common People", artist: "Pulp", year: 1995 },
    { id: "90s-019", title: "MMMBop", artist: "Hanson", year: 1997 },
    { id: "90s-020", title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
    { id: "90s-021", title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
    { id: "90s-022", title: "Believe", artist: "Cher", year: 1998 },
    { id: "90s-023", title: "Semi-Charmed Life", artist: "Third Eye Blind", year: 1997 },
    { id: "90s-024", title: "You Oughta Know", artist: "Alanis Morissette", year: 1995 },
    { id: "90s-025", title: "Ironic", artist: "Alanis Morissette", year: 1995 },
    { id: "90s-026", title: "Macarena", artist: "Los del Río", year: 1993 },
    { id: "90s-027", title: "Rhythm Is a Dancer", artist: "Snap!", year: 1992 },
    { id: "90s-028", title: "What Is Love", artist: "Haddaway", year: 1993 },
    { id: "90s-029", title: "Smack My Bitch Up", artist: "The Prodigy", year: 1997 },
    { id: "90s-030", title: "Firestarter", artist: "The Prodigy", year: 1996 },
    { id: "90s-031", title: "Barbie Girl", artist: "Aqua", year: 1997 },
    { id: "90s-032", title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990 },
    { id: "90s-033", title: "Jump Around", artist: "House of Pain", year: 1992 },
    { id: "90s-034", title: "Juicy", artist: "The Notorious B.I.G.", year: 1994 },
    { id: "90s-035", title: "California Love", artist: "2Pac", year: 1995 },
    { id: "90s-036", title: "Vogue", artist: "Madonna", year: 1990 },
    { id: "90s-037", title: "Wannabe", artist: "Spice Girls", year: 1996 },
    { id: "90s-038", title: "Say My Name", artist: "Destiny’s Child", year: 1999 },
    { id: "90s-039", title: "Genie in a Bottle", artist: "Christina Aguilera", year: 1999 },
    { id: "90s-040", title: "Basket Case", artist: "Green Day", year: 1994 },
    { id: "90s-041", title: "Two Princes", artist: "Spin Doctors", year: 1991 },
    { id: "90s-042", title: "Set Adrift on Memory Bliss", artist: "PM Dawn", year: 1991 },
    { id: "90s-043", title: "Iris", artist: "Goo Goo Dolls", year: 1998 },
    { id: "90s-044", title: "Don’t Look Back in Anger", artist: "Oasis", year: 1995 },
    { id: "90s-045", title: "Alive", artist: "Pearl Jam", year: 1991 },
    { id: "90s-046", title: "Thunderstruck", artist: "AC/DC", year: 1990 },
    { id: "90s-047", title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", year: 1997 },
    { id: "90s-048", title: "Quit Playing Games", artist: "Backstreet Boys", year: 1996 },
    { id: "90s-049", title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
    { id: "90s-050", title: "Tears in Heaven", artist: "Eric Clapton", year: 1992 }
  ],

  // =======================
  // 2000-TAL (50 låtar)
  // =======================
  "2000s": [
    { id: "00s-001", title: "Hey Ya!", artist: "OutKast", year: 2003 },
    { id: "00s-002", title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", year: 2003 },
    { id: "00s-003", title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
    { id: "00s-004", title: "Mr. Brightside", artist: "The Killers", year: 2003 },
    { id: "00s-005", title: "Umbrella", artist: "Rihanna ft. Jay-Z", year: 2007 },
    { id: "00s-006", title: "Rehab", artist: "Amy Winehouse", year: 2006 },
    { id: "00s-007", title: "Toxic", artist: "Britney Spears", year: 2003 },
    { id: "00s-008", title: "Viva la Vida", artist: "Coldplay", year: 2008 },
    { id: "00s-009", title: "Poker Face", artist: "Lady Gaga", year: 2008 },
    { id: "00s-010", title: "Lose Yourself", artist: "Eminem", year: 2002 },
    { id: "00s-011", title: "In the End", artist: "Linkin Park", year: 2000 },
    { id: "00s-012", title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
    { id: "00s-013", title: "I Gotta Feeling", artist: "The Black Eyed Peas", year: 2009 },
    { id: "00s-014", title: "Hips Don't Lie", artist: "Shakira", year: 2006 },
    { id: "00s-015", title: "Beautiful Day", artist: "U2", year: 2000 },
    { id: "00s-016", title: "Clocks", artist: "Coldplay", year: 2002 },
    { id: "00s-017", title: "Use Somebody", artist: "Kings of Leon", year: 2008 },
    { id: "00s-018", title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
    { id: "00s-019", title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
    { id: "00s-020", title: "A Thousand Miles", artist: "Vanessa Carlton", year: 2002 },
    { id: "00s-021", title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
    { id: "00s-022", title: "Hot N Cold", artist: "Katy Perry", year: 2008 },
    { id: "00s-023", title: "I Kissed a Girl", artist: "Katy Perry", year: 2008 },
    { id: "00s-024", title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },
    { id: "00s-025", title: "SexyBack", artist: "Justin Timberlake", year: 2006 },
    { id: "00s-026", title: "Family Affair", artist: "Mary J. Blige", year: 2001 },
    { id: "00s-027", title: "Yeah!", artist: "Usher", year: 2004 },
    { id: "00s-028", title: "Gold Digger", artist: "Kanye West", year: 2005 },
    { id: "00s-029", title: "Ignition (Remix)", artist: "R. Kelly", year: 2003 },
    { id: "00s-030", title: "In da Club", artist: "50 Cent", year: 2003 },
    { id: "00s-031", title: "Bring Me to Life", artist: "Evanescence", year: 2003 },
    { id: "00s-032", title: "How You Remind Me", artist: "Nickelback", year: 2001 },
    { id: "00s-033", title: "Complicated", artist: "Avril Lavigne", year: 2002 },
    { id: "00s-034", title: "Hurt", artist: "Christina Aguilera", year: 2006 },
    { id: "00s-035", title: "Hollaback Girl", artist: "Gwen Stefani", year: 2005 },
    { id: "00s-036", title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
    { id: "00s-037", title: "Drops of Jupiter", artist: "Train", year: 2001 },
    { id: "00s-038", title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
    { id: "00s-039", title: "The Scientist", artist: "Coldplay", year: 2002 },
    { id: "00s-040", title: "Numb", artist: "Linkin Park", year: 2003 },
    { id: "00s-041", title: "Bleeding Love", artist: "Leona Lewis", year: 2007 },
    { id: "00s-042", title: "Unwritten", artist: "Natasha Bedingfield", year: 2004 },
    { id: "00s-043", title: "Beautiful", artist: "Christina Aguilera", year: 2002 },
    { id: "00s-044", title: "Fallin'", artist: "Alicia Keys", year: 2001 },
    { id: "00s-045", title: "Empire State of Mind", artist: "Jay-Z & Alicia Keys", year: 2009 },
    { id: "00s-046", title: "Where Is the Love?", artist: "The Black Eyed Peas", year: 2003 },
    { id: "00s-047", title: "Mr. Saxobeat", artist: "Alexandra Stan", year: 2009 },
    { id: "00s-048", title: "Dani California", artist: "Red Hot Chili Peppers", year: 2006 },
    { id: "00s-049", title: "Harder Better Faster Stronger", artist: "Daft Punk", year: 2001 },
    { id: "00s-050", title: "Teenage Dirtbag", artist: "Wheatus", year: 2000 }
  ],

  // =======================
  // 2010-TAL (50 låtar)
  // =======================
  "2010s": [
    { id: "10s-001", title: "Rolling in the Deep", artist: "Adele", year: 2010 },
    { id: "10s-002", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: 2014 },
    { id: "10s-003", title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
    { id: "10s-004", title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
    { id: "10s-005", title: "Happy", artist: "Pharrell Williams", year: 2013 },
    { id: "10s-006", title: "Royals", artist: "Lorde", year: 2013 },
    { id: "10s-007", title: "Bad Romance", artist: "Lady Gaga", year: 2010 },
    { id: "10s-008", title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2011 },
    { id: "10s-009", title: "Someone Like You", artist: "Adele", year: 2011 },
    { id: "10s-010", title: "Get Lucky", artist: "Daft Punk", year: 2013 },
    { id: "10s-011", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis", year: 2012 },
    { id: "10s-012", title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
    { id: "10s-013", title: "Titanium", artist: "David Guetta", year: 2011 },
    { id: "10s-014", title: "Wake Me Up", artist: "Avicii", year: 2013 },
    { id: "10s-015", title: "Levels", artist: "Avicii", year: 2011 },
    { id: "10s-016", title: "We Found Love", artist: "Rihanna", year: 2011 },
    { id: "10s-017", title: "All of Me", artist: "John Legend", year: 2013 },
    { id: "10s-018", title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013 },
    { id: "10s-019", title: "Sorry", artist: "Justin Bieber", year: 2015 },
    { id: "10s-020", title: "Thank U, Next", artist: "Ariana Grande", year: 2018 },
    { id: "10s-021", title: "Havana", artist: "Camila Cabello", year: 2017 },
    { id: "10s-022", title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
    { id: "10s-023", title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018 },
    { id: "10s-024", title: "Take Me to Church", artist: "Hozier", year: 2013 },
    { id: "10s-025", title: "Lean On", artist: "Major Lazer & DJ Snake", year: 2015 },
    { id: "10s-026", title: "Closer", artist: "The Chainsmokers", year: 2016 },
    { id: "10s-027", title: "Starboy", artist: "The Weeknd", year: 2016 },
    { id: "10s-028", title: "Counting Stars", artist: "OneRepublic", year: 2013 },
    { id: "10s-029", title: "Despacito", artist: "Luis Fonsi", year: 2017 },
    { id: "10s-030", title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
    { id: "10s-031", title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
    { id: "10s-032", title: "Faded", artist: "Alan Walker", year: 2015 },
    { id: "10s-033", title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
    { id: "10s-034", title: "Timber", artist: "Pitbull ft. Ke$ha", year: 2013 },
    { id: "10s-035", title: "Grenade", artist: "Bruno Mars", year: 2010 },
    { id: "10s-036", title: "Locked Out of Heaven", artist: "Bruno Mars", year: 2012 },
    { id: "10s-037", title: "What Makes You Beautiful", artist: "One Direction", year: 2011 },
    { id: "10s-038", title: "Rude", artist: "MAGIC!", year: 2014 },
    { id: "10s-039", title: "Stressed Out", artist: "Twenty One Pilots", year: 2015 },
    { id: "10s-040", title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
    { id: "10s-041", title: "Believer", artist: "Imagine Dragons", year: 2017 },
    { id: "10s-042", title: "Chandelier", artist: "Sia", year: 2014 },
    { id: "10s-043", title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
    { id: "10s-044", title: "Roar", artist: "Katy Perry", year: 2013 },
    { id: "10s-045", title: "Earned It", artist: "The Weeknd", year: 2014 },
    { id: "10s-046", title: "Party Rock Anthem", artist: "LMFAO", year: 2011 },
    { id: "10s-047", title: "Stronger", artist: "Kelly Clarkson", year: 2011 },
    { id: "10s-048", title: "Die Young", artist: "Ke$ha", year: 2012 },
    { id: "10s-049", title: "The Hills", artist: "The Weeknd", year: 2015 },
    { id: "10s-050", title: "S&M", artist: "Rihanna", year: 2010 },
  ],

  // =======================
  // 2020-TAL (40 låtar)
  // =======================
  "2020s": [
    { id: "20s-001", title: "Blinding Lights", artist: "The Weeknd", year: 2020 },
    { id: "20s-002", title: "As It Was", artist: "Harry Styles", year: 2022 },
    { id: "20s-003", title: "Flowers", artist: "Miley Cyrus", year: 2023 },
    { id: "20s-004", title: "Bad Habits", artist: "Ed Sheeran", year: 2021 },
    { id: "20s-005", title: "Good 4 U", artist: "Olivia Rodrigo", year: 2021 },
    { id: "20s-006", title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
    { id: "20s-007", title: "Stay", artist: "The Kid LAROI & Justin Bieber", year: 2021 },
    { id: "20s-008", title: "Heat Waves", artist: "Glass Animals", year: 2020 },
    { id: "20s-009", title: "Levitating", artist: "Dua Lipa", year: 2020 },
    { id: "20s-010", title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
    { id: "20s-011", title: "Peaches", artist: "Justin Bieber", year: 2021 },
    { id: "20s-012", title: "WAP", artist: "Cardi B & Megan Thee Stallion", year: 2020 },
    { id: "20s-013", title: "Industry Baby", artist: "Lil Nas X", year: 2021 },
    { id: "20s-014", title: "abcdefu", artist: "GAYLE", year: 2021 },
    { id: "20s-015", title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", year: 2021 },
    { id: "20s-016", title: "About Damn Time", artist: "Lizzo", year: 2022 },
    { id: "20s-017", title: "Unholy", artist: "Sam Smith & Kim Petras", year: 2022 },
    { id: "20s-018", title: "Watermelon Sugar", artist: "Harry Styles", year: 2020 },
    { id: "20s-019", title: "Savage Love", artist: "Jason Derulo", year: 2020 },
    { id: "20s-020", title: "Kiss Me More", artist: "Doja Cat", year: 2021 },
    { id: "20s-021", title: "Break My Soul", artist: "Beyoncé", year: 2022 },
    { id: "20s-022", title: "Super Freaky Girl", artist: "Nicki Minaj", year: 2022 },
    { id: "20s-023", title: "Golden", artist: "Harry Styles", year: 2020 },
    { id: "20s-024", title: "Positions", artist: "Ariana Grande", year: 2020 },
    { id: "20s-025", title: "Ghost", artist: "Justin Bieber", year: 2021 },
    { id: "20s-026", title: "Shivers", artist: "Ed Sheeran", year: 2021 },
    { id: "20s-027", title: "Stay With Me", artist: "Calvin Harris", year: 2022 },
    { id: "20s-028", title: "First Class", artist: "Jack Harlow", year: 2022 },
    { id: "20s-029", title: "Sunroof", artist: "Nicky Youre", year: 2022 },
    { id: "20s-030", title: "I'm Good (Blue)", artist: "David Guetta & Bebe Rexha", year: 2022 },
    { id: "20s-031", title: "Running Up That Hill (Remix resurgence)", artist: "Kate Bush", year: 2022 },
    { id: "20s-032", title: "One Right Now", artist: "Post Malone & The Weeknd", year: 2021 },
    { id: "20s-033", title: "Late Night Talking", artist: "Harry Styles", year: 2022 },
    { id: "20s-034", title: "Hold Me Closer", artist: "Elton John & Britney Spears", year: 2022 },
    { id: "20s-035", title: "Lift Me Up", artist: "Rihanna", year: 2022 },
    { id: "20s-036", title: "My Universe", artist: "Coldplay & BTS", year: 2021 },
    { id: "20s-037", title: "Tití Me Preguntó", artist: "Bad Bunny", year: 2022 },
    { id: "20s-038", title: "Dakiti", artist: "Bad Bunny & Jhay Cortez", year: 2020 },
    { id: "20s-039", title: "Blinding Lights (TikTok Resurgence)", artist: "The Weeknd", year: 2020 },
    { id: "20s-040", title: "Where Are You Now", artist: "Lost Frequencies & Calum Scott", year: 2021 }
  ],
  // =======================
  // ROCK (50 låtar)
  // =======================
  "rock": [
    { id: "rock-001", title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
    { id: "rock-002", title: "Back in Black", artist: "AC/DC", year: 1980 },
    { id: "rock-003", title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
    { id: "rock-004", title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
    { id: "rock-005", title: "Hotel California", artist: "Eagles", year: 1976 },
    { id: "rock-006", title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
    { id: "rock-007", title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
    { id: "rock-008", title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
    { id: "rock-009", title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
    { id: "rock-010", title: "Another One Bites the Dust", artist: "Queen", year: 1980 },
    { id: "rock-011", title: "Highway to Hell", artist: "AC/DC", year: 1979 },
    { id: "rock-012", title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
    { id: "rock-013", title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
    { id: "rock-014", title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
    { id: "rock-015", title: "Enter Sandman", artist: "Metallica", year: 1991 },
    { id: "rock-016", title: "Paranoid", artist: "Black Sabbath", year: 1970 },
    { id: "rock-017", title: "Smoke on the Water", artist: "Deep Purple", year: 1972 },
    { id: "rock-018", title: "We Will Rock You", artist: "Queen", year: 1977 },
    { id: "rock-019", title: "We Are the Champions", artist: "Queen", year: 1977 },
    { id: "rock-020", title: "Dream On", artist: "Aerosmith", year: 1973 },
    { id: "rock-021", title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
    { id: "rock-022", title: "Welcome to the Jungle", artist: "Guns N' Roses", year: 1987 },
    { id: "rock-023", title: "I Love Rock 'n' Roll", artist: "Joan Jett", year: 1981 },
    { id: "rock-024", title: "Zombie", artist: "The Cranberries", year: 1994 },
    { id: "rock-025", title: "Basket Case", artist: "Green Day", year: 1994 },
    { id: "rock-026", title: "The Pretender", artist: "Foo Fighters", year: 2007 },
    { id: "rock-027", title: "My Sharona", artist: "The Knack", year: 1979 },
    { id: "rock-028", title: "You Give Love a Bad Name", artist: "Bon Jovi", year: 1986 },
    { id: "rock-029", title: "More Than a Feeling", artist: "Boston", year: 1976 },
    { id: "rock-030", title: "Barracuda", artist: "Heart", year: 1977 },
    { id: "rock-031", title: "The Kids Aren't Alright", artist: "The Offspring", year: 1998 },
    { id: "rock-032", title: "All the Small Things", artist: "Blink-182", year: 1999 },
    { id: "rock-033", title: "Run to the Hills", artist: "Iron Maiden", year: 1982 },
    { id: "rock-034", title: "Mr. Brightside", artist: "The Killers", year: 2003 },
    { id: "rock-035", title: "Best of You", artist: "Foo Fighters", year: 2005 },
    { id: "rock-036", title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
    { id: "rock-037", title: "Holiday", artist: "Green Day", year: 2004 },
    { id: "rock-038", title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
    { id: "rock-039", title: "Sharp Dressed Man", artist: "ZZ Top", year: 1983 },
    { id: "rock-040", title: "Black Betty", artist: "Ram Jam", year: 1977 },
    { id: "rock-041", title: "My Hero", artist: "Foo Fighters", year: 1997 },
    { id: "rock-042", title: "Everlong", artist: "Foo Fighters", year: 1997 },
    { id: "rock-043", title: "It's My Life", artist: "Bon Jovi", year: 2000 },
    { id: "rock-044", title: "When You Were Young", artist: "The Killers", year: 2006 },
    { id: "rock-045", title: "Numb", artist: "Linkin Park", year: 2003 },
    { id: "rock-046", title: "In the End", artist: "Linkin Park", year: 2000 },
    { id: "rock-047", title: "Brain Stew", artist: "Green Day", year: 1995 },
    { id: "rock-048", title: "Fat Lip", artist: "Sum 41", year: 2001 },
    { id: "rock-049", title: "Island in the Sun", artist: "Weezer", year: 2001 },
    { id: "rock-050", title: "Rebel Yell", artist: "Billy Idol", year: 1983 }
  ],

  // =======================
  // POP (50 låtar)
  // =======================
  "pop": [
    { id: "pop-001", title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
    { id: "pop-002", title: "Like a Prayer", artist: "Madonna", year: 1989 },
    { id: "pop-003", title: "Toxic", artist: "Britney Spears", year: 2003 },
    { id: "pop-004", title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
    { id: "pop-005", title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
    { id: "pop-006", title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
    { id: "pop-007", title: "Poker Face", artist: "Lady Gaga", year: 2008 },
    { id: "pop-008", title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
    { id: "pop-009", title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2011 },
    { id: "pop-010", title: "Happy", artist: "Pharrell Williams", year: 2013 },
    { id: "pop-011", title: "Rolling in the Deep", artist: "Adele", year: 2010 },
    { id: "pop-012", title: "Someone Like You", artist: "Adele", year: 2011 },
    { id: "pop-013", title: "Hello", artist: "Adele", year: 2015 },
    { id: "pop-014", title: "Uptown Funk", artist: "Mark Ronson & Bruno Mars", year: 2014 },
    { id: "pop-015", title: "Firework", artist: "Katy Perry", year: 2010 },
    { id: "pop-016", title: "Roar", artist: "Katy Perry", year: 2013 },
    { id: "pop-017", title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
    { id: "pop-018", title: "Blank Space", artist: "Taylor Swift", year: 2014 },
    { id: "pop-019", title: "Watermelon Sugar", artist: "Harry Styles", year: 2020 },
    { id: "pop-020", title: "As It Was", artist: "Harry Styles", year: 2022 },
    { id: "pop-021", title: "Levitating", artist: "Dua Lipa", year: 2020 },
    { id: "pop-022", title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
    { id: "pop-023", title: "Havana", artist: "Camila Cabello", year: 2017 },
    { id: "pop-024", title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
    { id: "pop-025", title: "Royals", artist: "Lorde", year: 2013 },
    { id: "pop-026", title: "Chandelier", artist: "Sia", year: 2014 },
    { id: "pop-027", title: "Cheap Thrills", artist: "Sia", year: 2016 },
    { id: "pop-028", title: "All About That Bass", artist: "Meghan Trainor", year: 2014 },
    { id: "pop-029", title: "Tik Tok", artist: "Ke$ha", year: 2009 },
    { id: "pop-030", title: "Timber", artist: "Pitbull & Ke$ha", year: 2013 },
    { id: "pop-031", title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018 },
    { id: "pop-032", title: "A Thousand Miles", artist: "Vanessa Carlton", year: 2002 },
    { id: "pop-033", title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
    { id: "pop-034", title: "Everytime We Touch", artist: "Cascada", year: 2005 },
    { id: "pop-035", title: "Genie in a Bottle", artist: "Christina Aguilera", year: 1999 },
    { id: "pop-036", title: "Beautiful", artist: "Christina Aguilera", year: 2002 },
    { id: "pop-037", title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
    { id: "pop-038", title: "Bye Bye Bye", artist: "*NSYNC", year: 2000 },
    { id: "pop-039", title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", year: 1997 },
    { id: "pop-040", title: "No Scrubs", artist: "TLC", year: 1999 },
    { id: "pop-041", title: "Say My Name", artist: "Destiny's Child", year: 1999 },
    { id: "pop-042", title: "Complicated", artist: "Avril Lavigne", year: 2002 },
    { id: "pop-043", title: "Sk8er Boi", artist: "Avril Lavigne", year: 2002 },
    { id: "pop-044", title: "Dark Horse", artist: "Katy Perry", year: 2013 },
    { id: "pop-045", title: "Positions", artist: "Ariana Grande", year: 2020 },
    { id: "pop-046", title: "Thank U, Next", artist: "Ariana Grande", year: 2018 },
    { id: "pop-047", title: "Blinding Lights", artist: "The Weeknd", year: 2020 },
    { id: "pop-048", title: "Earned It", artist: "The Weeknd", year: 2014 },
    { id: "pop-049", title: "Unwritten", artist: "Natasha Bedingfield", year: 2004 },
    { id: "pop-050", title: "I Knew You Were Trouble", artist: "Taylor Swift", year: 2012 }
  ],

  // =======================
  // METAL (40 låtar)
  // =======================
  "metal": [
    { id: "metal-001", title: "Enter Sandman", artist: "Metallica", year: 1991 },
    { id: "metal-002", title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
    { id: "metal-003", title: "Master of Puppets", artist: "Metallica", year: 1986 },
    { id: "metal-004", title: "Paranoid", artist: "Black Sabbath", year: 1970 },
    { id: "metal-005", title: "Iron Man", artist: "Black Sabbath", year: 1970 },
    { id: "metal-006", title: "Painkiller", artist: "Judas Priest", year: 1990 },
    { id: "metal-007", title: "Run to the Hills", artist: "Iron Maiden", year: 1982 },
    { id: "metal-008", title: "The Trooper", artist: "Iron Maiden", year: 1983 },
    { id: "metal-009", title: "Ace of Spades", artist: "Motörhead", year: 1980 },
    { id: "metal-010", title: "Chop Suey!", artist: "System of a Down", year: 2001 },
    { id: "metal-011", title: "Toxicity", artist: "System of a Down", year: 2001 },
    { id: "metal-012", title: "Duality", artist: "Slipknot", year: 2004 },
    { id: "metal-013", title: "Before I Forget", artist: "Slipknot", year: 2004 },
    { id: "metal-014", title: "Down with the Sickness", artist: "Disturbed", year: 2000 },
    { id: "metal-015", title: "Indestructible", artist: "Disturbed", year: 2008 },
    { id: "metal-016", title: "Hallowed Be Thy Name", artist: "Iron Maiden", year: 1982 },
    { id: "metal-017", title: "Symphony of Destruction", artist: "Megadeth", year: 1992 },
    { id: "metal-018", title: "Holy Wars", artist: "Megadeth", year: 1990 },
    { id: "metal-019", title: "The Number of the Beast", artist: "Iron Maiden", year: 1982 },
    { id: "metal-020", title: "Freak on a Leash", artist: "Korn", year: 1998 },
    { id: "metal-021", title: "Blind", artist: "Korn", year: 1994 },
    { id: "metal-022", title: "Psychosocial", artist: "Slipknot", year: 2008 },
    { id: "metal-023", title: "Fear of the Dark", artist: "Iron Maiden", year: 1992 },
    { id: "metal-024", title: "Raining Blood", artist: "Slayer", year: 1986 },
    { id: "metal-025", title: "Angel of Death", artist: "Slayer", year: 1986 },
    { id: "metal-026", title: "Walk", artist: "Pantera", year: 1992 },
    { id: "metal-027", title: "Cowboys from Hell", artist: "Pantera", year: 1990 },
    { id: "metal-028", title: "Roots Bloody Roots", artist: "Sepultura", year: 1996 },
    { id: "metal-029", title: "Enter Sandman (Live)", artist: "Metallica", year: 1992 },
    { id: "metal-030", title: "Sad But True", artist: "Metallica", year: 1991 },
    { id: "metal-031", title: "One", artist: "Metallica", year: 1988 },
    { id: "metal-032", title: "Battery", artist: "Metallica", year: 1986 },
    { id: "metal-033", title: "War Pigs", artist: "Black Sabbath", year: 1970 },
    { id: "metal-034", title: "Holy Diver", artist: "Dio", year: 1983 },
    { id: "metal-035", title: "Balls to the Wall", artist: "Accept", year: 1983 },
    { id: "metal-036", title: "Black No. 1", artist: "Type O Negative", year: 1993 },
    { id: "metal-037", title: "The Beautiful People", artist: "Marilyn Manson", year: 1996 },
    { id: "metal-038", title: "My Curse", artist: "Killswitch Engage", year: 2006 },
    { id: "metal-039", title: "Nemesis", artist: "Arch Enemy", year: 2005 },
    { id: "metal-040", title: "The Diary of Jane", artist: "Breaking Benjamin", year: 2006 }
  ],

  // =======================
  // HIPHOP (50 låtar)
  // =======================
  "hiphop": [
    { id: "hiphop-001", title: "Lose Yourself", artist: "Eminem", year: 2002 },
    { id: "hiphop-002", title: "Juicy", artist: "The Notorious B.I.G.", year: 1994 },
    { id: "hiphop-003", title: "California Love", artist: "2Pac & Dr. Dre", year: 1995 },
    { id: "hiphop-004", title: "Empire State of Mind", artist: "Jay-Z & Alicia Keys", year: 2009 },
    { id: "hiphop-005", title: "In da Club", artist: "50 Cent", year: 2003 },
    { id: "hiphop-006", title: "N.Y. State of Mind", artist: "Nas", year: 1994 },
    { id: "hiphop-007", title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017 },
    { id: "hiphop-008", title: "Sicko Mode", artist: "Travis Scott", year: 2018 },
    { id: "hiphop-009", title: "Gold Digger", artist: "Kanye West", year: 2005 },
    { id: "hiphop-010", title: "Jesus Walks", artist: "Kanye West", year: 2004 },
    { id: "hiphop-011", title: "The Way I Am", artist: "Eminem", year: 2000 },
    { id: "hiphop-012", title: "Without Me", artist: "Eminem", year: 2002 },
    { id: "hiphop-013", title: "Ms. Jackson", artist: "OutKast", year: 2000 },
    { id: "hiphop-014", title: "Still D.R.E.", artist: "Dr. Dre", year: 1999 },
    { id: "hiphop-015", title: "Forgot About Dre", artist: "Dr. Dre & Eminem", year: 1999 },
    { id: "hiphop-016", title: "Hotline Bling", artist: "Drake", year: 2015 },
    { id: "hiphop-017", title: "God’s Plan", artist: "Drake", year: 2018 },
    { id: "hiphop-018", title: "In My Feelings", artist: "Drake", year: 2018 },
    { id: "hiphop-019", title: "99 Problems", artist: "Jay-Z", year: 2003 },
    { id: "hiphop-020", title: "Big Pimpin'", artist: "Jay-Z", year: 2000 },
    { id: "hiphop-021", title: "Gin and Juice", artist: "Snoop Dogg", year: 1994 },
    { id: "hiphop-022", title: "Nuthin' But a 'G' Thang", artist: "Dr. Dre & Snoop Dogg", year: 1992 },
    { id: "hiphop-023", title: "Hypnotize", artist: "Notorious B.I.G.", year: 1997 },
    { id: "hiphop-024", title: "No Diggity", artist: "Blackstreet", year: 1996 },
    { id: "hiphop-025", title: "Mo Money Mo Problems", artist: "Notorious B.I.G.", year: 1997 },
    { id: "hiphop-026", title: "The Real Slim Shady", artist: "Eminem", year: 2000 },
    { id: "hiphop-027", title: "Stan", artist: "Eminem", year: 2000 },
    { id: "hiphop-028", title: "It Was a Good Day", artist: "Ice Cube", year: 1993 },
    { id: "hiphop-029", title: "Regulate", artist: "Warren G", year: 1994 },
    { id: "hiphop-030", title: "Sabotage", artist: "Beastie Boys", year: 1994 },
    { id: "hiphop-031", title: "Intergalactic", artist: "Beastie Boys", year: 1998 },
    { id: "hiphop-032", title: "Lose Control", artist: "Missy Elliott", year: 2005 },
    { id: "hiphop-033", title: "Work It", artist: "Missy Elliott", year: 2002 },
    { id: "hiphop-034", title: "All Falls Down", artist: "Kanye West", year: 2004 },
    { id: "hiphop-035", title: "Stronger", artist: "Kanye West", year: 2007 },
    { id: "hiphop-036", title: "Panda", artist: "Desiigner", year: 2015 },
    { id: "hiphop-037", title: "Rockstar", artist: "Post Malone", year: 2017 },
    { id: "hiphop-038", title: "Sunflower", artist: "Post Malone", year: 2018 },
    { id: "hiphop-039", title: "Mask Off", artist: "Future", year: 2017 },
    { id: "hiphop-040", title: "Trap Queen", artist: "Fetty Wap", year: 2014 },
    { id: "hiphop-041", title: "Thrift Shop", artist: "Macklemore", year: 2012 },
    { id: "hiphop-042", title: "Wild Thoughts", artist: "DJ Khaled", year: 2017 },
    { id: "hiphop-043", title: "Lucid Dreams", artist: "Juice WRLD", year: 2018 },
    { id: "hiphop-044", title: "Bad and Boujee", artist: "Migos", year: 2016 },
    { id: "hiphop-045", title: "Taste", artist: "Tyga", year: 2018 },
    { id: "hiphop-046", title: "Super Bass", artist: "Nicki Minaj", year: 2010 },
    { id: "hiphop-047", title: "Only", artist: "Nicki Minaj", year: 2014 },
    { id: "hiphop-048", title: "Bodak Yellow", artist: "Cardi B", year: 2017 },
    { id: "hiphop-049", title: "Money", artist: "Cardi B", year: 2018 },
    { id: "hiphop-050", title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", year: 2021 }
  ],

  // =======================
  // EDM / DANCE (50 låtar)
  // =======================
  "edm": [
    { id: "edm-001", title: "Levels", artist: "Avicii", year: 2011 },
    { id: "edm-002", title: "Wake Me Up", artist: "Avicii", year: 2013 },
    { id: "edm-003", title: "Titanium", artist: "David Guetta & Sia", year: 2011 },
    { id: "edm-004", title: "Hey Brother", artist: "Avicii", year: 2013 },
    { id: "edm-005", title: "Don't You Worry Child", artist: "Swedish House Mafia", year: 2012 },
    { id: "edm-006", title: "Greyhound", artist: "Swedish House Mafia", year: 2012 },
    { id: "edm-007", title: "One (Your Name)", artist: "Swedish House Mafia", year: 2010 },
    { id: "edm-008", title: "Animals", artist: "Martin Garrix", year: 2013 },
    { id: "edm-009", title: "Scary Monsters and Nice Sprites", artist: "Skrillex", year: 2010 },
    { id: "edm-010", title: "Bangarang", artist: "Skrillex", year: 2011 },
    { id: "edm-011", title: "Clarity", artist: "Zedd", year: 2012 },
    { id: "edm-012", title: "Lean On", artist: "Major Lazer", year: 2015 },
    { id: "edm-013", title: "Cold Water", artist: "Major Lazer", year: 2016 },
    { id: "edm-014", title: "Turn Down for What", artist: "DJ Snake", year: 2013 },
    { id: "edm-015", title: "Faded", artist: "Alan Walker", year: 2015 },
    { id: "edm-016", title: "Alone", artist: "Marshmello", year: 2016 },
    { id: "edm-017", title: "Happier", artist: "Marshmello", year: 2018 },
    { id: "edm-018", title: "Silence", artist: "Marshmello", year: 2017 },
    { id: "edm-019", title: "Strobe", artist: "Deadmau5", year: 2009 },
    { id: "edm-020", title: "Ghosts ’n’ Stuff", artist: "Deadmau5", year: 2008 },
    { id: "edm-021", title: "I Remember", artist: "Kaskade & Deadmau5", year: 2008 },
    { id: "edm-022", title: "We Found Love", artist: "Rihanna & Calvin Harris", year: 2011 },
    { id: "edm-023", title: "Summer", artist: "Calvin Harris", year: 2014 },
    { id: "edm-024", title: "Feel So Close", artist: "Calvin Harris", year: 2011 },
    { id: "edm-025", title: "This Is What You Came For", artist: "Calvin Harris", year: 2016 },
    { id: "edm-026", title: "Where Them Girls At", artist: "David Guetta", year: 2011 },
    { id: "edm-027", title: "Turn Me On", artist: "David Guetta & Nicki Minaj", year: 2011 },
    { id: "edm-028", title: "Memories", artist: "David Guetta", year: 2010 },
    { id: "edm-029", title: "Blue Monday (Eric Prydz Remix)", artist: "New Order", year: 2014 },
    { id: "edm-030", title: "Call on Me", artist: "Eric Prydz", year: 2004 },
    { id: "edm-031", title: "Pjanoo", artist: "Eric Prydz", year: 2008 },
    { id: "edm-032", title: "One Kiss", artist: "Dua Lipa & Calvin Harris", year: 2018 },
    { id: "edm-033", title: "Head & Heart", artist: "Joel Corry & MNEK", year: 2020 },
    { id: "edm-034", title: "Stolen Dance", artist: "Milky Chance", year: 2013 },
    { id: "edm-035", title: "Waiting All Night", artist: "Rudimental", year: 2013 },
    { id: "edm-036", title: "Don’t You Want Me", artist: "Felix", year: 1992 },
    { id: "edm-037", title: "Blue (Da Ba Dee)", artist: "Eiffel 65", year: 1999 },
    { id: "edm-038", title: "Sandstorm", artist: "Darude", year: 1999 },
    { id: "edm-039", title: "Better Off Alone", artist: "Alice Deejay", year: 1999 },
    { id: "edm-040", title: "Castles in the Sky", artist: "Ian Van Dahl", year: 2000 },
    { id: "edm-041", title: "Insomnia", artist: "Faithless", year: 1995 },
    { id: "edm-042", title: "Born Slippy", artist: "Underworld", year: 1996 },
    { id: "edm-043", title: "Destination Calabria", artist: "Alex Gaudino", year: 2007 },
    { id: "edm-044", title: "Don’t You Worry Child", artist: "Swedish House Mafia", year: 2012 },
    { id: "edm-045", title: "Firestone", artist: "Kygo", year: 2014 },
    { id: "edm-046", title: "It Ain't Me", artist: "Kygo & Selena Gomez", year: 2017 },
    { id: "edm-047", title: "Sun Is Shining", artist: "Axwell Ʌ Ingrosso", year: 2015 },
    { id: "edm-048", title: "Reload", artist: "Sebastian Ingrosso & Tommy Trash", year: 2012 },
    { id: "edm-049", title: "Runaway (U & I)", artist: "Galantis", year: 2014 },
    { id: "edm-050", title: "Peanut Butter Jelly", artist: "Galantis", year: 2015 }
  ],
  // =======================
  // SOUL & R&B (50 låtar)
  // =======================
  "soul": [
    { id: "soul-001", title: "Respect", artist: "Aretha Franklin", year: 1967 },
    { id: "soul-002", title: "What's Going On", artist: "Marvin Gaye", year: 1971 },
    { id: "soul-003", title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell", year: 1967 },
    { id: "soul-004", title: "Superstition", artist: "Stevie Wonder", year: 1972 },
    { id: "soul-005", title: "Lean on Me", artist: "Bill Withers", year: 1972 },
    { id: "soul-006", title: "Lovely Day", artist: "Bill Withers", year: 1977 },
    { id: "soul-007", title: "Let's Stay Together", artist: "Al Green", year: 1971 },
    { id: "soul-008", title: "A Change Is Gonna Come", artist: "Sam Cooke", year: 1964 },
    { id: "soul-009", title: "Sittin' On The Dock of the Bay", artist: "Otis Redding", year: 1968 },
    { id: "soul-010", title: "Ain't No Sunshine", artist: "Bill Withers", year: 1971 },
    { id: "soul-011", title: "Sexual Healing", artist: "Marvin Gaye", year: 1982 },
    { id: "soul-012", title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
    { id: "soul-013", title: "No Scrubs", artist: "TLC", year: 1999 },
    { id: "soul-014", title: "Waterfalls", artist: "TLC", year: 1995 },
    { id: "soul-015", title: "Say My Name", artist: "Destiny's Child", year: 1999 },
    { id: "soul-016", title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
    { id: "soul-017", title: "Halo", artist: "Beyoncé", year: 2008 },
    { id: "soul-018", title: "If I Ain't Got You", artist: "Alicia Keys", year: 2004 },
    { id: "soul-019", title: "Fallin'", artist: "Alicia Keys", year: 2001 },
    { id: "soul-020", title: "Kiss from a Rose", artist: "Seal", year: 1994 },
    { id: "soul-021", title: "Ordinary People", artist: "John Legend", year: 2004 },
    { id: "soul-022", title: "All of Me", artist: "John Legend", year: 2013 },
    { id: "soul-023", title: "Rock With You", artist: "Michael Jackson", year: 1979 },
    { id: "soul-024", title: "Ain't Nobody", artist: "Chaka Khan", year: 1983 },
    { id: "soul-025", title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", year: 1968 },
    { id: "soul-026", title: "My Girl", artist: "The Temptations", year: 1964 },
    { id: "soul-027", title: "September", artist: "Earth, Wind & Fire", year: 1978 },
    { id: "soul-028", title: "Best of My Love", artist: "The Emotions", year: 1977 },
    { id: "soul-029", title: "Just the Two of Us", artist: "Grover Washington Jr.", year: 1981 },
    { id: "soul-030", title: "Return of the Mack", artist: "Mark Morrison", year: 1996 },
    { id: "soul-031", title: "No Diggity", artist: "Blackstreet", year: 1996 },
    { id: "soul-032", title: "Back to Black", artist: "Amy Winehouse", year: 2006 },
    { id: "soul-033", title: "Rehab", artist: "Amy Winehouse", year: 2006 },
    { id: "soul-034", title: "Un-Break My Heart", artist: "Toni Braxton", year: 1996 },
    { id: "soul-035", title: "Irreplaceable", artist: "Beyoncé", year: 2006 },
    { id: "soul-036", title: "End of the Road", artist: "Boyz II Men", year: 1992 },
    { id: "soul-037", title: "When a Man Loves a Woman", artist: "Percy Sledge", year: 1966 },
    { id: "soul-038", title: "All Night Long", artist: "Lionel Richie", year: 1983 },
    { id: "soul-039", title: "Get Lucky", artist: "Daft Punk ft. Pharrell", year: 2013 },
    { id: "soul-040", title: "Treasure", artist: "Bruno Mars", year: 2013 },
    { id: "soul-041", title: "Locked Out of Heaven", artist: "Bruno Mars", year: 2012 },
    { id: "soul-042", title: "Blame It on the Boogie", artist: "The Jacksons", year: 1978 },
    { id: "soul-043", title: "I Want You Back", artist: "Jackson 5", year: 1969 },
    { id: "soul-044", title: "Man in the Mirror", artist: "Michael Jackson", year: 1988 },
    { id: "soul-045", title: "Smooth Criminal", artist: "Michael Jackson", year: 1987 },
    { id: "soul-046", title: "Scream", artist: "Michael & Janet Jackson", year: 1995 },
    { id: "soul-047", title: "Adorn", artist: "Miguel", year: 2012 },
    { id: "soul-048", title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
    { id: "soul-049", title: "No One", artist: "Alicia Keys", year: 2007 },
    { id: "soul-050", title: "Thinking Bout You", artist: "Frank Ocean", year: 2012 }
  ],

  // =======================
  // COUNTRY (40 låtar)
  // =======================
  "country": [
    { id: "country-001", title: "Jolene", artist: "Dolly Parton", year: 1973 },
    { id: "country-002", title: "Take Me Home, Country Roads", artist: "John Denver", year: 1971 },
    { id: "country-003", title: "Ring of Fire", artist: "Johnny Cash", year: 1963 },
    { id: "country-004", title: "9 to 5", artist: "Dolly Parton", year: 1980 },
    { id: "country-005", title: "The Gambler", artist: "Kenny Rogers", year: 1978 },
    { id: "country-006", title: "Friends in Low Places", artist: "Garth Brooks", year: 1990 },
    { id: "country-007", title: "Crazy", artist: "Patsy Cline", year: 1961 },
    { id: "country-008", title: "I Walk the Line", artist: "Johnny Cash", year: 1956 },
    { id: "country-009", title: "Man! I Feel Like a Woman!", artist: "Shania Twain", year: 1997 },
    { id: "country-010", title: "You're Still the One", artist: "Shania Twain", year: 1998 },
    { id: "country-011", title: "Wide Open Spaces", artist: "Dixie Chicks", year: 1998 },
    { id: "country-012", title: "Before He Cheats", artist: "Carrie Underwood", year: 2005 },
    { id: "country-013", title: "Need You Now", artist: "Lady A", year: 2009 },
    { id: "country-014", title: "Wagon Wheel", artist: "Darius Rucker", year: 2013 },
    { id: "country-015", title: "Chicken Fried", artist: "Zac Brown Band", year: 2008 },
    { id: "country-016", title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
    { id: "country-017", title: "Achy Breaky Heart", artist: "Billy Ray Cyrus", year: 1992 },
    { id: "country-018", title: "Body Like a Back Road", artist: "Sam Hunt", year: 2017 },
    { id: "country-019", title: "Cruise", artist: "Florida Georgia Line", year: 2012 },
    { id: "country-020", title: "Die a Happy Man", artist: "Thomas Rhett", year: 2015 },
    { id: "country-021", title: "Blue Ain’t Your Color", artist: "Keith Urban", year: 2016 },
    { id: "country-022", title: "Fancy", artist: "Reba McEntire", year: 1990 },
    { id: "country-023", title: "Forever and Ever, Amen", artist: "Randy Travis", year: 1987 },
    { id: "country-024", title: "Mama Tried", artist: "Merle Haggard", year: 1968 },
    { id: "country-025", title: "Islands in the Stream", artist: "Kenny Rogers & Dolly Parton", year: 1983 },
    { id: "country-026", title: "Bless the Broken Road", artist: "Rascal Flatts", year: 2004 },
    { id: "country-027", title: "Boot Scootin’ Boogie", artist: "Brooks & Dunn", year: 1991 },
    { id: "country-028", title: "Something in the Orange", artist: "Zach Bryan", year: 2022 },
    { id: "country-029", title: "Tennessee Whiskey", artist: "Chris Stapleton", year: 2015 },
    { id: "country-030", title: "Girl Crush", artist: "Little Big Town", year: 2014 },
    { id: "country-031", title: "Burning House", artist: "Cam", year: 2015 },
    { id: "country-032", title: "Hurricane", artist: "Luke Combs", year: 2016 },
    { id: "country-033", title: "Beer Never Broke My Heart", artist: "Luke Combs", year: 2019 },
    { id: "country-034", title: "Take Your Time", artist: "Sam Hunt", year: 2014 },
    { id: "country-035", title: "This Kiss", artist: "Faith Hill", year: 1998 },
    { id: "country-036", title: "Breathe", artist: "Faith Hill", year: 1999 },
    { id: "country-037", title: "Live Like You Were Dying", artist: "Tim McGraw", year: 2004 },
    { id: "country-038", title: "Humble and Kind", artist: "Tim McGraw", year: 2015 },
    { id: "country-039", title: "American Honey", artist: "Lady A", year: 2010 },
    { id: "country-040", title: "Strawberry Wine", artist: "Deana Carter", year: 1996 }
  ],

  // =======================
  // SOUNDTRACKS / MOVIES (50 låtar)
  // =======================
  "soundtracks": [
    { id: "ost-001", title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
    { id: "ost-002", title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
    { id: "ost-003", title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
    { id: "ost-004", title: "Ghostbusters", artist: "Ray Parker Jr.", year: 1984 },
    { id: "ost-005", title: "Footloose", artist: "Kenny Loggins", year: 1984 },
    { id: "ost-006", title: "Danger Zone", artist: "Kenny Loggins", year: 1986 },
    { id: "ost-007", title: "Take My Breath Away", artist: "Berlin", year: 1986 },
    { id: "ost-008", title: "I Don't Want to Miss a Thing", artist: "Aerosmith", year: 1998 },
    { id: "ost-009", title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018 },
    { id: "ost-010", title: "Let It Go", artist: "Idina Menzel", year: 2013 },
    { id: "ost-011", title: "Into the Unknown", artist: "Idina Menzel", year: 2019 },
    { id: "ost-012", title: "Circle of Life", artist: "The Lion King", year: 1994 },
    { id: "ost-013", title: "Can You Feel the Love Tonight", artist: "Elton John", year: 1994 },
    { id: "ost-014", title: "Hakuna Matata", artist: "The Lion King", year: 1994 },
    { id: "ost-015", title: "You've Got a Friend in Me", artist: "Randy Newman", year: 1995 },
    { id: "ost-016", title: "I Believe I Can Fly", artist: "R. Kelly", year: 1996 },
    { id: "ost-017", title: "Staying Alive", artist: "Bee Gees", year: 1977 },
    { id: "ost-018", title: "Unchained Melody", artist: "The Righteous Brothers", year: 1965 },
    { id: "ost-019", title: "The Power of Love", artist: "Huey Lewis & the News", year: 1985 },
    { id: "ost-020", title: "Colors of the Wind", artist: "Vanessa Williams", year: 1995 },
    { id: "ost-021", title: "All Star", artist: "Smash Mouth", year: 1999 },
    { id: "ost-022", title: "Men in Black", artist: "Will Smith", year: 1997 },
    { id: "ost-023", title: "The Greatest Show", artist: "The Greatest Showman", year: 2017 },
    { id: "ost-024", title: "This Is Me", artist: "The Greatest Showman", year: 2017 },
    { id: "ost-025", title: "Rewrite the Stars", artist: "The Greatest Showman", year: 2017 },
    { id: "ost-026", title: "City of Stars", artist: "La La Land", year: 2016 },
    { id: "ost-027", title: "Skyfall", artist: "Adele", year: 2012 },
    { id: "ost-028", title: "No Time to Die", artist: "Billie Eilish", year: 2020 },
    { id: "ost-029", title: "Heathens", artist: "Twenty One Pilots", year: 2016 },
    { id: "ost-030", title: "Sunflower", artist: "Post Malone", year: 2018 },
    { id: "ost-031", title: "Immortals", artist: "Fall Out Boy", year: 2014 },
    { id: "ost-032", title: "Believer", artist: "Imagine Dragons", year: 2017 },
    { id: "ost-033", title: "The Hanging Tree", artist: "Jennifer Lawrence", year: 2014 },
    { id: "ost-034", title: "We Don't Talk About Bruno", artist: "Encanto", year: 2021 },
    { id: "ost-035", title: "Surface Pressure", artist: "Encanto", year: 2021 },
    { id: "ost-036", title: "Live and Let Die", artist: "Paul McCartney", year: 1973 },
    { id: "ost-037", title: "Gonna Fly Now", artist: "Rocky", year: 1976 },
    { id: "ost-038", title: "Everybody’s Talking", artist: "Harry Nilsson", year: 1969 },
    { id: "ost-039", title: "Flashdance… What a Feeling", artist: "Irene Cara", year: 1983 },
    { id: "ost-040", title: "Fame", artist: "Irene Cara", year: 1980 },
    { id: "ost-041", title: "Footloose", artist: "Kenny Loggins", year: 1984 },
    { id: "ost-042", title: "I’m a Believer", artist: "Smash Mouth", year: 2001 },
    { id: "ost-043", title: "Holding Out for a Hero", artist: "Bonnie Tyler", year: 1984 },
    { id: "ost-044", title: "Time of My Life", artist: "Dirty Dancing", year: 1987 },
    { id: "ost-045", title: "Don't You (Forget About Me)", artist: "Simple Minds", year: 1985 },
    { id: "ost-046", title: "Stayin’ Alive", artist: "Bee Gees", year: 1977 },
    { id: "ost-047", title: "A Million Dreams", artist: "The Greatest Showman", year: 2017 },
    { id: "ost-048", title: "Let It Grow", artist: "The Lorax / Ester Dean", year: 2012 },
    { id: "ost-049", title: "I'll Make a Man Out of You", artist: "Mulan", year: 1998 },
    { id: "ost-050", title: "You’re the One That I Want", artist: "Grease", year: 1978 }
  ],

  // =======================
  // SVENSK POP (50 låtar)
  // =======================
  "svenskpop": [
    { id: "sp-001", title: "Om du lämnade mig nu", artist: "Lars Winnerbäck & Miss Li", year: 2007 },
    { id: "sp-002", title: "Utan dina andetag", artist: "Kent", year: 1997 },
    { id: "sp-003", title: "Välkommen in", artist: "Veronica Maggio", year: 2011 },
    { id: "sp-004", title: "Jag kommer", artist: "Veronica Maggio", year: 2011 },
    { id: "sp-005", title: "Euphoria", artist: "Loreen", year: 2012 },
    { id: "sp-006", title: "Sommaren är kort", artist: "Tomas Ledin", year: 1982 },
    { id: "sp-007", title: "En kväll i juni", artist: "Lasse Berghagen", year: 1971 },
    { id: "sp-008", title: "Astrologen", artist: "Vivii", year: 2018 },
    { id: "sp-009", title: "Alla vill till himmelen", artist: "Timbuktu", year: 2005 },
    { id: "sp-010", title: "En del av mitt hjärta", artist: "Tomas Ledin", year: 1987 },
    { id: "sp-011", title: "Känn ingen sorg", artist: "Håkan Hellström", year: 2000 },
    { id: "sp-012", title: "Kom igen Lena!", artist: "Håkan Hellström", year: 2002 },
    { id: "sp-013", title: "Din tid kommer", artist: "Håkan Hellström", year: 2013 },
    { id: "sp-014", title: "Snälla bli min", artist: "Veronica Maggio", year: 2010 },
    { id: "sp-015", title: "Gråa dagar", artist: "Miriam Bryant", year: 2014 },
    { id: "sp-016", title: "Black Car", artist: "Miriam Bryant", year: 2015 },
    { id: "sp-017", title: "Dance You Off", artist: "Benjamin Ingrosso", year: 2018 },
    { id: "sp-018", title: "Tror du att han bryr sig", artist: "Benjamin Ingrosso", year: 2018 },
    { id: "sp-019", title: "Tystnar i luren", artist: "Ana Diaz", year: 2016 },
    { id: "sp-020", title: "Det kommer bli bra", artist: "Bo Kaspers Orkester", year: 2019 },
    { id: "sp-021", title: "Sunnanvind", artist: "Maia Hirasawa", year: 2007 },
    { id: "sp-022", title: "Cara Mia", artist: "Måns Zelmerlöw", year: 2007 },
    { id: "sp-023", title: "Heroes", artist: "Måns Zelmerlöw", year: 2015 },
    { id: "sp-024", title: "Hårdrock halleluja", artist: "Lordi (Finland)", year: 2006 },
    { id: "sp-025", title: "Fångad av en stormvind", artist: "Carola", year: 1991 },
    { id: "sp-026", title: "Stad i ljus", artist: "Tommy Körberg", year: 1988 },
    { id: "sp-027", title: "När vi två blir en", artist: "Gyllene Tider", year: 1979 },
    { id: "sp-028", title: "Sommartider", artist: "Gyllene Tider", year: 1982 },
    { id: "sp-029", title: "The Look", artist: "Roxette", year: 1988 },
    { id: "sp-030", title: "Listen to Your Heart", artist: "Roxette", year: 1988 },
    { id: "sp-031", title: "It Must Have Been Love", artist: "Roxette", year: 1990 },
    { id: "sp-032", title: "Young Folks", artist: "Peter Bjorn and John", year: 2006 },
    { id: "sp-033", title: "Från och med du", artist: "Oskar Linnros", year: 2010 },
    { id: "sp-034", title: "Tänd alla ljus", artist: "Hanna Ferm", year: 2018 },
    { id: "sp-035", title: "Lush Life", artist: "Zara Larsson", year: 2015 },
    { id: "sp-036", title: "Uncover", artist: "Zara Larsson", year: 2013 },
    { id: "sp-037", title: "Ain't My Fault", artist: "Zara Larsson", year: 2016 },
    { id: "sp-038", title: "All the Feels", artist: "Renaida", year: 2018 },
    { id: "sp-039", title: "Running with Lions", artist: "Alice", year: 2017 },
    { id: "sp-040", title: "Cry", artist: "Dotter", year: 2020 },
    { id: "sp-041", title: "Bulletproof", artist: "Dotter", year: 2020 },
    { id: "sp-042", title: "Tjugonde", artist: "Thomas Stenström", year: 2023 },
    { id: "sp-043", title: "Ser du månen där du är ikväll", artist: "Thomas Stenström", year: 2014 },
    { id: "sp-044", title: "Slå mig hårt i ansiktet", artist: "Thomas Stenström", year: 2013 },
    { id: "sp-045", title: "Hon dansar vidare i livet", artist: "Hov1", year: 2018 },
    { id: "sp-046", title: "Vindar på Mars", artist: "Darwin", year: 2021 },
    { id: "sp-047", title: "Sverige", artist: "Kent", year: 1995 },
    { id: "sp-048", title: "Dom andra", artist: "Kent", year: 2002 },
    { id: "sp-049", title: "Vi två 17 år", artist: "Molly Sandén", year: 2015 },
    { id: "sp-050", title: "Himlen runt hörnet", artist: "Lisa Nilsson", year: 1992 }
  ],

  // =======================
  // DANSBAND (40 låtar)
  // =======================
  "dansband": [
    { id: "db-001", title: "Inget stoppar oss nu", artist: "Blackjack", year: 1989 },
    { id: "db-002", title: "Sången till livet", artist: "Vikingarna", year: 1988 },
    { id: "db-003", title: "Leende guldbruna ögon", artist: "Vikingarna", year: 1977 },
    { id: "db-004", title: "Hallå Världen", artist: "Drifters", year: 1996 },
    { id: "db-005", title: "Vad har du under blusen Rut?", artist: "Schytts", year: 1973 },
    { id: "db-006", title: "Om himlen och Österlen", artist: "Danne Stråhed", year: 1993 },
    { id: "db-007", title: "Gråt inga tårar", artist: "Thorleifs", year: 1974 },
    { id: "db-008", title: "Änglahund", artist: "Hasse Andersson", year: 1982 },
    { id: "db-009", title: "En kväll i juni", artist: "Lasse Berghagen", year: 1971 },
    { id: "db-010", title: "Till mitt eget blue Hawaii", artist: "Vikingarna", year: 1978 },
    { id: "db-011", title: "Du ringde från Flen", artist: "Grönwalls", year: 1994 },
    { id: "db-012", title: "Dej ska jag älska all min tid", artist: "Wizex", year: 1989 },
    { id: "db-013", title: "Bang en boomerang", artist: "Svenne & Lotta", year: 1975 },
    { id: "db-014", title: "Lyckliga gatan", artist: "Anna-Lena Löfgren", year: 1967 },
    { id: "db-015", title: "Kinnasvalsen", artist: "Wizex", year: 1983 },
    { id: "db-016", title: "Främling", artist: "Carola", year: 1983 },
    { id: "db-017", title: "Eviva España", artist: "Vikingarna", year: 1973 },
    { id: "db-018", title: "Högt över havet", artist: "Arja Saijonmaa", year: 1987 },
    { id: "db-019", title: "Krafter förenas", artist: "Shine", year: 2004 },
    { id: "db-020", title: "En sländas dans", artist: "Jigs", year: 1975 },
    { id: "db-021", title: "Aj aj aj", artist: "Schytts", year: 1973 },
    { id: "db-022", title: "De sista ljuva åren", artist: "Lasse Stefanz", year: 1989 },
    { id: "db-023", title: "Dag efter dag", artist: "Chips", year: 1982 },
    { id: "db-024", title: "Michelangelo", artist: "Björn Skifs", year: 1975 },
    { id: "db-025", title: "Här kommer alla känslorna", artist: "Gyllene Tider", year: 2004 },
    { id: "db-026", title: "Sommar och sol", artist: "Sven-Ingvars", year: 1966 },
    { id: "db-027", title: "Kristina från Vilhelmina", artist: "Lasse Stefanz", year: 2011 },
    { id: "db-028", title: "Det börjar verka kärlek banne mig", artist: "Claes-Göran Hederström", year: 1968 },
    { id: "db-029", title: "Eloise", artist: "Arvingarna", year: 1993 },
    { id: "db-030", title: "Boogie Woogie Bugle Boy", artist: "The Andrews Sisters", year: 1941 },
    { id: "db-031", title: "Tusen och en natt", artist: "Charlotte Nilsson", year: 1999 },
    { id: "db-032", title: "Dra dit pepparn växer", artist: "Drifters", year: 1996 },
    { id: "db-033", title: "Dover–Calais", artist: "Style", year: 1986 },
    { id: "db-034", title: "Oh Boy", artist: "Peps Blodsband", year: 1975 },
    { id: "db-035", title: "Mio min Mio", artist: "Agnetha Fältskog", year: 1987 },
    { id: "db-036", title: "Jag ringer på fredag", artist: "Sven-Ingvars", year: 1967 },
    { id: "db-037", title: "Sommar sommar sol", artist: "Sven-Ingvars", year: 1966 },
    { id: "db-038", title: "Stephanie", artist: "Blackjack", year: 1989 },
    { id: "db-039", title: "Hon kommer med solsken", artist: "Östen med Resten", year: 1995 },
    { id: "db-040", title: "Det börjar verka kärlek", artist: "Lill-Babs", year: 1968 }
  ],

  // =======================
  // ONE-HIT WONDERS (50 låtar)
  // =======================
  "onehit": [
    { id: "oh-001", title: "Take On Me", artist: "a-ha", year: 1984 },
    { id: "oh-002", title: "Somebody That I Used to Know", artist: "Gotye", year: 2011 },
    { id: "oh-003", title: "What Is Love", artist: "Haddaway", year: 1993 },
    { id: "oh-004", title: "Blue (Da Ba Dee)", artist: "Eiffel 65", year: 1999 },
    { id: "oh-005", title: "Barbie Girl", artist: "Aqua", year: 1997 },
    { id: "oh-006", title: "Macarena", artist: "Los del Río", year: 1993 },
    { id: "oh-007", title: "Mambo No. 5", artist: "Lou Bega", year: 1999 },
    { id: "oh-008", title: "Tainted Love", artist: "Soft Cell", year: 1981 },
    { id: "oh-009", title: "Come on Eileen", artist: "Dexys Midnight Runners", year: 1982 },
    { id: "oh-010", title: "Bittersweet Symphony", artist: "The Verve", year: 1997 },
    { id: "oh-011", title: "Spirit in the Sky", artist: "Norman Greenbaum", year: 1969 },
    { id: "oh-012", title: "I'm Too Sexy", artist: "Right Said Fred", year: 1991 },
    { id: "oh-013", title: "You Get What You Give", artist: "New Radicals", year: 1998 },
    { id: "oh-014", title: "No Rain", artist: "Blind Melon", year: 1992 },
    { id: "oh-015", title: "Who Let the Dogs Out", artist: "Baha Men", year: 2000 },
    { id: "oh-016", title: "The Ketchup Song", artist: "Las Ketchup", year: 2002 },
    { id: "oh-017", title: "Cotton Eye Joe", artist: "Rednex", year: 1994 },
    { id: "oh-018", title: "Walking on Sunshine", artist: "Katrina & The Waves", year: 1983 },
    { id: "oh-019", title: "Tubthumping", artist: "Chumbawamba", year: 1997 },
    { id: "oh-020", title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
    { id: "oh-021", title: "Africa", artist: "Toto", year: 1982 },
    { id: "oh-022", title: "Video Killed the Radio Star", artist: "The Buggles", year: 1979 },
    { id: "oh-023", title: "Breakfast at Tiffany’s", artist: "Deep Blue Something", year: 1993 },
    { id: "oh-024", title: "Rico Suave", artist: "Gerardo", year: 1990 },
    { id: "oh-025", title: "Toy Soldiers", artist: "Martika", year: 1988 },
    { id: "oh-026", title: "4 Non Blondes – What's Up?", artist: "4 Non Blondes", year: 1992 },
    { id: "oh-027", title: "MMMBop", artist: "Hanson", year: 1997 },
    { id: "oh-028", title: "Kung Fu Fighting", artist: "Carl Douglas", year: 1974 },
    { id: "oh-029", title: "I’m Gonna Be (500 Miles)", artist: "The Proclaimers", year: 1988 },
    { id: "oh-030", title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990 },
    { id: "oh-031", title: "Stereo Love", artist: "Edward Maya", year: 2009 },
    { id: "oh-032", title: "Dragostea Din Tei", artist: "O-Zone", year: 2003 },
    { id: "oh-033", title: "The Fox (What Does the Fox Say?)", artist: "Ylvis", year: 2012 },
    { id: "oh-034", title: "All the Things She Said", artist: "t.A.T.u.", year: 2002 },
    { id: "oh-035", title: "Bad Day", artist: "Daniel Powter", year: 2005 },
    { id: "oh-036", title: "Take Me to Church", artist: "Hozier", year: 2014 },
    { id: "oh-037", title: "Riptide", artist: "Vance Joy", year: 2013 },
    { id: "oh-038", title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
    { id: "oh-039", title: "Pumped Up Kicks", artist: "Foster the People", year: 2011 },
    { id: "oh-040", title: "Safe and Sound", artist: "Capital Cities", year: 2011 },
    { id: "oh-041", title: "Stolen Dance", artist: "Milky Chance", year: 2013 },
    { id: "oh-042", title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
    { id: "oh-043", title: "The Safety Dance", artist: "Men Without Hats", year: 1982 },
    { id: "oh-044", title: "You Spin Me Round", artist: "Dead or Alive", year: 1984 },
    { id: "oh-045", title: "Blue Monday", artist: "New Order", year: 1983 },
    { id: "oh-046", title: "Do You Believe in Love", artist: "Huey Lewis", year: 1982 },
    { id: "oh-047", title: "Somebody's Watching Me", artist: "Rockwell", year: 1984 },
    { id: "oh-048", title: "My Sharona", artist: "The Knack", year: 1979 },
    { id: "oh-049", title: "Come and Get Your Love", artist: "Redbone", year: 1973 },
    { id: "oh-050", title: "Hooked on a Feeling", artist: "Blue Swede", year: 1973 }
  ],

    // =======================
  // SVENSK MELLO – TOPP 50
  // =======================
  "svensk_mello": [
    { id: "mello-001", title: "Euphoria", artist: "Loreen", year: 2012 },
    { id: "mello-002", title: "Tattoo", artist: "Loreen", year: 2023 },
    { id: "mello-003", title: "Heroes", artist: "Måns Zelmerlöw", year: 2015 },
    { id: "mello-004", title: "Fångad av en stormvind", artist: "Carola", year: 1991 },
    { id: "mello-005", title: "Främling", artist: "Carola", year: 1983 },
    { id: "mello-006", title: "Evighet", artist: "Carola", year: 2006 },
    { id: "mello-007", title: "Stad i ljus", artist: "Tommy Körberg", year: 1988 },
    { id: "mello-008", title: "Det gör ont", artist: "Lena Philipsson", year: 2004 },
    { id: "mello-009", title: "Òla Ôla", artist: "Andreas Johnson", year: 2006 },
    { id: "mello-010", title: "Moving On", artist: "Sarah Dawn Finer", year: 2009 },
    
    { id: "mello-011", title: "När vindarna viskar mitt namn", artist: "Roger Pontare", year: 2000 },
    { id: "mello-012", title: "As It Is", artist: "Molly Hammar", year: 2015 },
    { id: "mello-013", title: "Cara Mia", artist: "Måns Zelmerlöw", year: 2007 },
    { id: "mello-014", title: "Begging", artist: "Anton Ewald", year: 2013 },
    { id: "mello-015", title: "Undo", artist: "Sanna Nielsen", year: 2014 },
    { id: "mello-016", title: "Kom", artist: "Timoteij", year: 2010 },
    { id: "mello-017", title: "La Voix", artist: "Malena Ernman", year: 2009 },
    { id: "mello-018", title: "In The Club", artist: "Danny Saucedo", year: 2011 },
    { id: "mello-019", title: "Amazing", artist: "Danny Saucedo", year: 2012 },
    { id: "mello-020", title: "If I Were Sorry", artist: "Frans", year: 2016 },

    { id: "mello-021", title: "Dance You Off", artist: "Benjamin Ingrosso", year: 2018 },
    { id: "mello-022", title: "Kingdom Come", artist: "Anna Bergendahl", year: 2020 },
    { id: "mello-023", title: "Ashes to Ashes", artist: "Anna Bergendahl", year: 2019 },
    { id: "mello-024", title: "Too Late for Love", artist: "John Lundvik", year: 2019 },
    { id: "mello-025", title: "The Mamas – Move", artist: "The Mamas", year: 2020 },
    { id: "mello-026", title: "Voices", artist: "Tusse", year: 2021 },
    { id: "mello-027", title: "Blame It on the Disco", artist: "Alcazar", year: 2014 },
    { id: "mello-028", title: "Stay the Night", artist: "Alcazar", year: 2009 },
    { id: "mello-029", title: "This Is the World We Live In", artist: "Alcazar", year: 2003 },
    { id: "mello-030", title: "In i dimman", artist: "Medina", year: 2022 },

    { id: "mello-031", title: "Renaida – All the Feels", artist: "Renaida", year: 2018 },
    { id: "mello-032", title: "Bulletproof", artist: "Dotter", year: 2020 },
    { id: "mello-033", title: "Little Tot", artist: "Dotter", year: 2021 },
    { id: "mello-034", title: "Bada Nakna", artist: "Samir & Viktor", year: 2016 },
    { id: "mello-035", title: "Groupie", artist: "Samir & Viktor", year: 2015 },
    { id: "mello-036", title: "Shuffla", artist: "Samir & Viktor", year: 2018 },
    { id: "mello-037", title: "Eloise", artist: "Arvingarna", year: 1993 },
    { id: "mello-038", title: "I Do", artist: "Arvingarna", year: 2019 },
    { id: "mello-039", title: "Håll om mig", artist: "Nanne Grönvall", year: 2005 },
    { id: "mello-040", title: "Avundsjuk", artist: "Nanne Grönvall", year: 1998 },

    { id: "mello-041", title: "Låt Oss Tala Känslor", artist: "Lasse Berghagen", year: 1975 },
    { id: "mello-042", title: "Sonia", artist: "Lasse Holm & Monica Törnell", year: 1986 },
    { id: "mello-043", title: "Diggiloo Diggiley", artist: "Herreys", year: 1984 },
    { id: "mello-044", title: "Eloise", artist: "Arvingarna", year: 1993 },
    { id: "mello-045", title: "Tusen och en natt", artist: "Charlotte Nilsson (Perrelli)", year: 1999 },
    { id: "mello-046", title: "Mirakel", artist: "Björn Ranelid & Sara Li", year: 2012 },
    { id: "mello-047", title: "Jag ljuger så bra", artist: "Linda Bengtzing", year: 2006 },
    { id: "mello-048", title: "Alla flickor", artist: "Linda Bengtzing", year: 2005 },
    { id: "mello-049", title: "Ingen som du", artist: "Sonja Aldén", year: 2007 },
    { id: "mello-050", title: "Blessed", artist: "Liamo", year: 2023 }
  ],

  };
// ========================
// Helper: Slumpa låtar
// ========================
export function getRandomSongs(categories, count) {
  const allSongs = [];

  categories.forEach(cat => {
    if (songCategories[cat]) {
      allSongs.push(...songCategories[cat]);
    }
  });

  // Shuffla
  const shuffled = allSongs.sort(() => Math.random() - 0.5);

  // Begränsa antal
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// ========================
// Tillgängliga kategorier
// ========================
export const availableCategories = [
  { id: "50s", name: "50-tal", count: 40 },
  { id: "60s", name: "60-tal", count: 50 },
  { id: "70s", name: "70-tal", count: 50 },
  { id: "80s", name: "80-tal", count: 50 },
  { id: "90s", name: "90-tal", count: 55 },
  { id: "2000s", name: "2000-tal", count: 50 },
  { id: "2010s", name: "2010-tal", count: 50 },
  { id: "2020s", name: "2020-tal", count: 50 },

  { id: "rock", name: "Rock", count: 50 },
  { id: "pop", name: "Pop", count: 50 },
  { id: "metal", name: "Metal", count: 40 },
  { id: "hiphop", name: "Hip Hop", count: 50 },
  { id: "edm", name: "EDM / Dance", count: 50 },

  { id: "soul", name: "Soul & R&B", count: 50 },
  { id: "country", name: "Country", count: 40 },
  { id: "soundtracks", name: "Soundtracks", count: 50 },

  { id: "svenskpop", name: "Svensk pop", count: 50 },
  { id: "dansband", name: "Dansband", count: 40 },

  { id: "onehit", name: "One Hit Wonders", count: 50 },
  { id: "svensk_mello", name: "Svensk Mello", count: 50 }
];
